name: Go

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go '1.22.x'
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Test
        run: go test ./...

      - name: Build
        run: go build -v ./cmd/gjq
